meshery-extensions/meshery-linkerd

linkerd/client.go
linkerd/install.go
linkerd/linkerd.go
linkerd/yaml.go
main.go

- fix for install issue
- fixed broken builds due to rename fro LinkeredClient to Client
- removed "to solve" comment from all over the place
Signed-off-by: Girish Ranganathan <girish.rranganathan@gmail.com>

fix for install issue

---

README.md

fix build status badge, ref #13

---

linkerd/client.go

in line 32 client was declared as Client

Client should be client: problem was capital c

---

linkerd/install.go
linkerd/linkerd.go

the URLSuffix was exported, that why we were getting error
fixes #24

made a small change

---

README.md

See issue #27, I just added a few links.

README.md: add links to badges

---

.github/ISSUE_TEMPLATE/documentation.md
README.md

Signed-off-by: gunjanmimo <gunjan.mtbpaul@gmail.com>

#31 documentation GitHub issue template added to Linkerd adapter repo

---

.github/workflows/ci.yml

Signed-off-by: nupur-thakur <nupur.s.thakur@gmail.com>

Update ci.yml with static error checks of Go Code 

---

.github/workflows/ci.yml

Fixed Issue: #45 
The PR just for making a quick test. Hi,@leecalcote, welcome to do any discussion around this action. You can get all the information you want at the address below:
https://github.com/marketplace/actions/kind-kubernetes-in-docker-action

Add the KinD (Kubernetes in Docker) Action for testing

---

.github/workflows/ci.yml

Fixed issue #45 
Remove extra step of KinD

Remove the extra steps of KinD

---

.github/workflows/ci.yml
go.sum
linkerd/install.go
linkerd/linkerd.go

Fix the issue gosec-G306 G307

---

.github/workflows/ci.yml
linkerd/client_test.go

Add the unitest for Newclient function

---

.github/workflows/ci.yml
linkerd/install_test.go

Add the unit test case for download linkerd-cli and install linkerd to the Kubernetes cluster

---

.github/workflows/ci.yml
.gitignore
linkerd/client_test.go
linkerd/install.go
linkerd/install_test.go
linkerd/linkerd.go
pkg/util/io_util_test.go

* Changed to download Linkerd-cli of the latest stable version
* Changed the unit test cases to hit error just failed

Changed to download Linkerd-cli of the latest stable version

---

README.md

Signed-off-by: Ruth-ikegah <ruthikegah@gmail.com>

Update Contributor to Community on Readme

---

README.md

Signed-off-by: Adeola 46505882+Adeola-Adesoba@users.noreply.github.com

Update Meshery Community to Layer5 Community

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Signed-off-by: anita-ihuman <charlesanita403@gmail.com>

 Added Release Drafter for this repository

---

Dockerfile
linkerd/linkerd.go

fixed install issues

---

go.mod
go.sum
linkerd/install.go
linkerd/linkerd.go
linkerd/supported_ops.go

changes for annotation injection

---

linkerd/config_templates/istiobookinfo.yaml

[Workloads] Fresh BookInfo Manifest

---

linkerd/linkerd.go

fixed sample app install issue

---

linkerd/install.go
linkerd/linkerd.go
linkerd/supported_ops.go

[Workloads] Support for deploying NGINX Ingress Controller

---

linkerd/linkerd.go

fixes for namespace deployment

---

.github/workflows/ci.yml
Makefile
go.mod
go.sum
linkerd/client_test.go
linkerd/install.go
linkerd/install_test.go
linkerd/linkerd.go
pkg/util/io_util_test.go

Signed-off-by: aisuko <urakiny@gmail.com>
The PR includes local-check script and remove the functions which according to the `golangci-lint` checks, you can run `make local-check` command and to validate the code

fixed local checks

---

linkerd/linkerd.go

This PR fixes #109 
Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

Fix service lookup referenced in issue: #109

---

Dockerfile
go.mod
go.sum
linkerd/smi_conformance.go

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
This PR fixes #144

[SMI] Fixed SMI conformance test startup

---

go.mod
go.sum
internal/config/config.go
internal/config/operations.go
linkerd/linkerd.go
linkerd/sample_apps.go

added annotation config

---

linkerd/linkerd.go
linkerd/sample_apps.go

fixes for ci

---

go.mod
go.sum

Signed-off-by: Utkarsh Srivastava <srivastavautkarsh8097@gmail.com>

Update to meshery-adapter-library v0.1.17

---

README.md

Not able to assign issue to myself, will need one of the repo owners to do it for me if possible. I have added comment in the issue also :smile_cat: 
Could someone kindly take a look at this and suggest areas to improve?
This is my first ever contribution to a public open source project, so apologies for any errors... :cat2: 
Thanks a million!

#189 [README] Update README Community Section

---

.github/ISSUE_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml

Signed-off-by: debjani1413 <deydebjani916@gmail.com>
Description
Changing layer5 link to meshery link

Updated the ISSUE_TEMPLATE

---

README.md

fixes slack icon in readme and adds community forum in readme
This PR fixes #201  and #202  

[README] fixes slack icon and adds community forum

---

internal/config/config.go

Signed-off-by: debjani1413 <deydebjani916@gmail.com>

SMP protos compliant operation name for Linkerd

---

internal/config/releases.go

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
* Thanks to @utkarsh-pro for the quick tip :stuck_out_tongue: 

[Lifecycle] quick fix for install operation not working

---

Dockerfile
go.mod
go.sum
internal/config/config.go
linkerd/error.go
linkerd/install.go
linkerd/linkerd.go
linkerd/oam.go
linkerd/oam/doc.go
linkerd/oam/parser.go
linkerd/oam/register.go
main.go
templates/oam/traits/automaticsidecarinjection.Linkerd.meshery.layer5io.schema.json
templates/oam/traits/automaticsidecarinjection.Linkerd_definition.json
templates/oam/workloads/linkerdmesh.meshery.layer5io.schema.json
templates/oam/workloads/linkerdmesh_definition.json

This PR adds support for Patterns.
DO NOT MERGE, DRAFT PR.

Add support for patterns

---

.github/workflows/update-oam-defs.yml

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
This PR fixes #220 

pattern components generator

---

Dockerfile

Signed-off-by: aisuko <urakiny@gmail.com>

[Draft] Bump the distroless image tag to fix cves

---

.github/workflows/build-and-release.yml
.github/workflows/ci.yml
go.mod
go.sum
internal/config/config.go
internal/config/operations.go
linkerd/addons.go
linkerd/error.go
linkerd/install.go
linkerd/linkerd.go
linkerd/oam.go
linkerd/sample_apps.go
templates/oam/patches/service-loadbalancer.json
templates/oam/workloads/jaegerlinkerdaddon.meshery.layer5io.schema.json
templates/oam/workloads/jaegerlinkerdaddon_definition.json
templates/oam/workloads/linkerdmesh_definition.json
templates/oam/workloads/multiclusterlinkerdaddon.meshery.layer5io.schema.json
templates/oam/workloads/multiclusterlinkerdaddon_definition.json
templates/oam/workloads/smilinkerdaddon.meshery.layer5io.schema.json
templates/oam/workloads/smilinkerdaddon_definition.json
templates/oam/workloads/vizlinkerdaddon.meshery.layer5io.schema.json
templates/oam/workloads/vizlinkerdaddon_definition.json

Adding linkerd extensions support via meshops as well as patternops

---

main.go
templates/oam/workloads/jaegerlinkerdaddon_definition.json
templates/oam/workloads/linkerdmesh_definition.json
templates/oam/workloads/multiclusterlinkerdaddon_definition.json
templates/oam/workloads/smilinkerdaddon_definition.json
templates/oam/workloads/vizlinkerdaddon_definition.json

fixed typo from definitions

---

.github/workflows/ci.yml
internal/config/config.go
internal/config/operations.go
internal/config/releases.go

Signed-off-by: aisuko <urakiny@gmail.com>
We got the CI issue with go statticcheck, but when I was check it at local, it doesn't report any error. So, I'd like to update the CI process to follow the latest official Github Action example and to solve this.https://staticcheck.io/docs/running-staticcheck/github-actions/

Fixed CI state issue

---

README.md

The discourse shield is added to README.md and the whole shield section is aligned in centre for better experience.
Kindly review if there’s any error please let me know, Thank you.
Signed-off-by: Swapnil Bhabal (swapnilbhabal787@gmail.com)

The discourse shield is added successfully.

---

.github/workflows/update-oam-defs.yml

Fix oam component check

---

internal/config/operations.go
internal/config/releases.go
main.go

Use new meshkit function

---

helpers/component_info.json

Update the name of adapter in `component_info.json` for uniformity on naming components

updated adapter name in component_info.json

---

.github/install/deploy.yaml
.github/workflows/e2etests.yaml

Add e2e Workflow

---

.github/workflows/e2etests.yaml

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>

Fix timestamp

---

.github/workflows/e2etests.yaml
linkerd/error.go
main.go

Signed-off-by: Aditya Chatterjee <speak2adi@gmail.com>
minor updates

minor updates

---

main.go

Signed-off-by: asubedy <frexpe@pm.me>

changed version none to edge

---

.github/dependabot.yml

Add Ashish in reviewers

---

linkerd/install.go

Fix failing linkerd installation

---

.github/workflows/e2etests.yaml

This PR fixes e2e tests by testing on stable releases of linkerd

Fix failing e2e tests

---

build/config.go
internal/config/config.go

Fix slow start of adapter due to older github clone function

---

linkerd/install.go

Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
This PR fixes failing helm install due to meshkit version update.

Fix helm install

---

helpers/component_info.json
internal/config/error.go
linkerd/error.go

Fix duplicate error codes

---

.github/workflows/ci.yml

Signed-off-by: Axit Patel <patelakshit2025@gmail.com>
This PR fixes #341 
Update go version in ci.yml file

update go version 

---

.github/workflows/update-oam-defs.yml

Signed-off-by: Srinivas karnati <karnatisrinivasulareddy@gmail.com>
This PR fixes #346 

updated the components generator workflow

---

Makefile
build/Makefile.core.mk
build/Makefile.show-help.mk

Signed-off-by: leecalcote <leecalcote@gmail.com>

[CI] Normalize makefile

---

Dockerfile

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Remove AMD hardcoding and kubeopenapi

---

go.mod
go.sum

Upgrade meshkit/adapter-library

---

go.mod
go.sum
linkerd/linkerd.go

Signed-off-by: MUzairS15 <muzair.shaikh810@gmail.com>
This PR enables sending complete error details to client;
1. Error Code
2. Cause
3. Remedy
4. Component Type
5. Component Name

Send detailed error response to client

---

go.mod
go.sum
linkerd/linkerd.go
linkerd/oam.go
main.go

Add EventStreamer for notification centre

---

.github/workflows/multi-platform.yml

Signed-off-by: Bishal das <70086051+bishal7679@users.noreply.github.com>
Fixed the wrong docker release tags in this adapters.
This PR fixes 
https://github.com/meshery/meshery/issues/6408

Fixed the wrong docker release tags in this adapters

---

Makefile
build/Makefile.core.mk
linkerd/error.go

Signed-off-by: Antonette Caldwell <pullmana8@gmail.com>
This PR relaxes Go 1.19 requirement.

Relaxed Go requirement

---

internal/config/operations.go
linkerd/install.go

Fix failed linkerd installation with MeshOps V1

---

linkerd/install.go

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Use linkerd-crds and linkerd-control-plane charts for install

---

go.mod
go.sum
linkerd/oam.go

Signed-off-by: lolverae <alberto.olvera.espinosa@gmail.com>
This PR repeats whats been done on the Linkerd adapter https://github.com/meshery/meshery-istio/pull/532

Upgrade meshkit with meshmodel changes

---

.github/dependabot.yml
.github/label-commenter-config.yml
.github/workflows/build-and-release.yml
.github/workflows/ci.yml
.github/workflows/error-ref-publisher.yaml
.github/workflows/label-commenter.yml
.github/workflows/multi-platform.yml
.github/workflows/newcomers-alert.yml
.github/workflows/release-drafter.yml
.github/workflows/slack.yml

This PR propagates some of the workflows for this adapter, from the Istio adapter, including styling, jobs and version pinning.

[CI] Propagate workflows from Istio

---

internal/config/operations.go

Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

Change Helm URL for addons

---

.github/config.yml

change the image link in firstPRMergeComment

---

CODEOWNERS

Please take a look this blog which is related to the owner syntax. https://github.blog/changelog/2022-02-17-codeowners-improvements-syntax-errors-preview-of-who-will-be-requested-and-more/

Fix invalid  code owner syntax

---

.github/workflows/e2etests.yaml

deploy linkerd stable channel

---

.github/install/deploy.yaml
build/config.go
main.go

This PR adds missing model name in deploy.yaml used for testing deployment of Linkerd service mesh.
This PR fixes https://github.com/meshery/meshery-linkerd/issues/515

[CI] Fix E2E test

---

.github/workflows/e2etests.yaml

This updates the incorrect logic for determine latest adapter release.

[CI] Update e2etests.yaml

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/documentation.md
.github/ISSUE_TEMPLATE/feature_request.md

fix: updated figma links in issue template

---

build/config.go
main.go

update refrence path for spec

---

go.mod
go.sum

fix build failure

---

.github/workflows/e2etests.yaml

Update upload-artifact and download-artifact actions version to v4
This PR fixes:
- [Discussion](https://layer5io.slack.com/archives/C011VPREG2Z/p1714388851226509)

Update upload-artifact and download-artifact actions version to v4

---

Dockerfile

Update Dockerfile to use Go version 1.23

---

CONTRIBUTING.md
Dockerfile
Makefile
README.md

fix: update docker repository references from layer5io to meshery

---

.github/workflows/build-and-release.yml
.github/workflows/ci.yml
.github/workflows/error-ref-publisher.yaml
.github/workflows/label-commenter.yml
.github/workflows/multi-platform.yml
.github/workflows/newcomers-alert.yml
.github/workflows/release-drafter.yml
.github/workflows/slack.yml

- Towards  https://github.com/meshery/meshery/issues/13754
- Updated the runner image from ubuntu-22.04 to ubuntu-24.04.

Update GitHub Actions runner from ubuntu-22.04 to ubuntu-24.04

---

.github/workflows/slack.yml

Updated Slack.yml according to asked for repos under meshery-extensions
